# Generated by Django 6.0.1 on 2026-03-09 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opdday',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_patient_per_day',
        ),
        migrations.AddField(
            model_name='booking',
            name='consulting_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='consulting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='queue_insert_time',
            field=models.DateTimeField(blank=True, help_text='When patient joined the active queue (after confirmation)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opdday',
            name='avg_consult_minutes',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='opdday',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('offline', 'Offline (Walk-in)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning (10AM – 12PM)'), ('evening', 'Evening (3PM – 5PM)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('waiting', 'Waiting'), ('consulting', 'Consulting'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='walkin_name',
            field=models.CharField(blank=True, help_text='Name for walk-in patients', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opdday',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opd_days', to='accounts.doctor'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('patient__isnull', False)), fields=('patient', 'booking_date'), name='unique_patient_per_day'),
        ),
    ]
