# Generated by Django 6.0.1 on 2026-03-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('booking', '0002_alter_opdday_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_patient_per_day',
        ),
        migrations.AlterField(
            model_name='booking',
            name='queue_insert_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='walkin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('patient__isnull', False)), fields=('patient', 'doctor', 'session', 'booking_date'), name='unique_patient_per_doctor_session'),
        ),
    ]
