# Generated by Django 6.0.1 on 2026-03-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_unique_patient_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='near_queue_notified',
            field=models.BooleanField(default=False),
        ),
    ]
