# Generated by Django 6.0.1 on 2026-03-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_opdday_add_session'),
        ('booking', '0004_booking_near_queue_notified'),
    ]

    operations = [
    ]
