# Generated by Django 6.0.1 on 2026-03-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_merge_20260322_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdday',
            name='confirmation_prompt_sent',
            field=models.BooleanField(default=False),
        ),
    ]
